### ISSUE TITLE
mobile ui - logo and link not aligned

### ISSUE THREAD

**Issue by asha-hegde** [ajency/binary-flux#10]
in mobile UI, the AWS logo and the link "All data sources" are no aligned vertically.

In desktop UI, it appears to be aligned vertically

**Suggestion:** have the logo & the link, center-aligned @jeromie 

**actual ui - mobile:**
![b16](https://user-images.githubusercontent.com/51397558/70797246-1e77fa00-1dca-11ea-8f8b-94ae2f7ac02e.png)

**desktop ui -**
![b17](https://user-images.githubusercontent.com/51397558/70797308-40717c80-1dca-11ea-9e81-e8fe225806fb.png)

**Comment by jeromie** [comment]
I would suggest keep the logo left aligned on mobile so that its placement below the link appears same as it does on desktop.
