### ISSUE TITLE
LHS tabs must be inlined 

### ISSUE THREAD

**Issue by asha-hegde** [ajency/binary-flux#12]
The LHS tabs "Web API" and ""Custom" must be in-line

**expected UI:**
![b5](https://user-images.githubusercontent.com/51397558/70888940-7485b100-2007-11ea-86d5-7897c6d91123.png)

**actual ui:**
![b4](https://user-images.githubusercontent.com/51397558/70888946-794a6500-2007-11ea-9701-810079ab55a4.png)

**Comment by jeromie** [comment]
@asha-hegde what screen size is this?

**Comment by asha-hegde** [comment]
1400px
