### ISSUE TITLE
content tabs - separator missing 

### ISSUE THREAD

**Issue by asha-hegde** [ajency/binary-flux#30]
**expected:**
![b37](https://user-images.githubusercontent.com/51397558/70899907-af92df00-201d-11ea-86d6-427a265c79c6.png)

**actual:**
![b38](https://user-images.githubusercontent.com/51397558/70899921-b3befc80-201d-11ea-9890-5ab15d41bd95.png)

**Comment by asha-hegde** [comment]
seperator appears too bright and too thin 

**expected:**
![b4](https://user-images.githubusercontent.com/51397558/71029299-1f47bd80-2135-11ea-8b26-fc4b2c335724.png)


**actual:**
![b3](https://user-images.githubusercontent.com/51397558/71029309-240c7180-2135-11ea-8a35-a58c056eae4b.png)

**Comment by Vaibhavarolkar** [comment]
@asha-hegde in design width of the separator is 1px.
