### ISSUE TITLE
navtab - highlighted menu-item in caps 

### ISSUE THREAD

**Issue by asha-hegde** [ajency/binary-flux#5]
navtab - the highlighted menu-item "JD EDWARDS" needs to be in caps as per requirement.

**Doubt:** @jeromie is only that particular menu-item to be in caps or all highlighted(active) menu-item needs to be changed to caps?

expected ui:
![b6](https://user-images.githubusercontent.com/51397558/70794143-ede09200-1dc2-11ea-8083-e8fe970b2ee8.png)

**actual ui:**
![b7](https://user-images.githubusercontent.com/51397558/70794175-005acb80-1dc3-11ea-870c-1356f7eb2799.png)

**Comment by jeromie** [comment]
have updated so that only that tab is in caps by default. caps dont change based on active tab.
