### ISSUE TITLE
LHS menu strip - shadow must be darker 

### ISSUE THREAD

**Issue by asha-hegde** [ajency/binary-flux#52]
**expected:**
![b14](https://user-images.githubusercontent.com/51397558/70993309-be4ac600-20f1-11ea-9f77-fa01a85bd440.png)

**actual:**
![b15](https://user-images.githubusercontent.com/51397558/70993313-c30f7a00-20f1-11ea-85ca-ea7b1e60735d.png)

**Comment by Vaibhavarolkar** [comment]
@asha-hegde Have used same box shadow from design.
