### ISSUE TITLE
alpha-numeric field - ellipsis 

### ISSUE THREAD

**Issue by asha-hegde** [ajency/binary-flux#53]
designs show "ellipsis" when text entered goes beyond the scope of the textbox.

@jeromie does this need to be applied in the designs while entering data?

**expected:**
![b16](https://user-images.githubusercontent.com/51397558/70993494-28fc0180-20f2-11ea-916f-6caf003e75de.png)

**actual:**
![b17](https://user-images.githubusercontent.com/51397558/70993510-2ef1e280-20f2-11ea-89fb-eda0d60a6ad6.png)

**Comment by jeromie** [comment]
no, this can be ignored.
