### ISSUE TITLE
add button - text to be made thicker 

### ISSUE THREAD

**Issue by asha-hegde** [ajency/binary-flux#56]
**expected:**
![b23](https://user-images.githubusercontent.com/51397558/70995332-4f23a080-20f6-11ea-802f-519db901a98b.png)

**actual:**
![b22](https://user-images.githubusercontent.com/51397558/70995338-5480eb00-20f6-11ea-844d-99ece1ec3d7e.png)

**Comment by asha-hegde** [comment]
text still looks thin.

**expected:**
![b1](https://user-images.githubusercontent.com/51397558/71027339-1228cf80-2131-11ea-87af-86d008c97af2.png)


**actual:**
![j15](https://user-images.githubusercontent.com/51397558/71027355-17861a00-2131-11ea-8ee2-d00487e6f297.png)

**Comment by Vaibhavarolkar** [comment]
@asha-hegde We have used font weight 700, can't increase more than that.
