### ISSUE TITLE
mobile UI - search box missing 

### ISSUE THREAD

**Issue by asha-hegde** [ajency/binary-flux#62]
design shows a search box on the LHS :

![b28](https://user-images.githubusercontent.com/51397558/70997740-b3952e80-20fb-11ea-9eb0-7a14e666165a.png)

**video showing the mobile ui with search box missing in popup:**
https://www.loom.com/share/ac0fb49d55734c30a418e66f44664c3f

**Comment by asha-hegde** [comment]
the 'x' button is missing within the search box, which appears when text is entered - in actual **iphone / ipad** device

![b1](https://user-images.githubusercontent.com/51397558/71056255-8d64a280-217e-11ea-9932-6a2b3ba18061.png)

**Comment by asha-hegde** [comment]
issue exists

**Comment by jeromie** [comment]
@asha-hegde this can be ignored. it's ios behaviour for search field.
