### ISSUE TITLE
LHS column - width appears to be less 

### ISSUE THREAD

**Issue by asha-hegde** [ajency/binary-flux#69]
**expected: width - 255px**
![b9](https://user-images.githubusercontent.com/51397558/71090593-6a131500-21c9-11ea-9c3d-c257a114cfab.png)

**actual: width - 227px**
![b10](https://user-images.githubusercontent.com/51397558/71090611-75fed700-21c9-11ea-96f8-444e4f57628f.png)

**Comment by asha-hegde** [comment]
issue still exists

**Comment by ankitasangodkar** [comment]
@jeromie  i have used bootstrap classes to display column. Please confirm whether to use bootstrap class or fixed width i.e 255px for sidebar.

**Comment by jeromie** [comment]
@ankitasangodkar use custom class here to get proper width.
