### ISSUE TITLE
mobile ui - heading-desc - placement of "edit" button 

### ISSUE THREAD

**Issue by asha-hegde** [ajency/binary-flux#86]
would be appropriate to fix the "edit" icon to the right of the screen, to make the UI look better

@jeromie kindly review the suggestion

![b39](https://user-images.githubusercontent.com/51397558/71238272-b70dfd00-2329-11ea-88f7-f6fd8d89513f.png)

**Comment by jeromie** [comment]
agreed. Edit can be fixed to the right on mobile screens as per Asha's suggestion.
