### ISSUE TITLE
mobile UI - comment/example strip to be moved to the right 

### ISSUE THREAD

**Issue by asha-hegde** [ajency/binary-flux#87]
would be appropriate to fix the "comment/example" strip to the right of the screen, to make the UI look better

@jeromie kindly review the suggestion

![b39](https://user-images.githubusercontent.com/51397558/71238852-20424000-232b-11ea-8c92-6e93df8cbdba.png)

**Comment by jeromie** [comment]
I think this can be kept as it is. No need for a change.
