### ISSUE TITLE
mobile - portrait UI - url strip and save button 

### ISSUE THREAD

**Issue by asha-hegde** [ajency/binary-flux#88]
Suggestion:
for mobile UI - portrait mode

1. Make the url strip cover the entire row -> will make entering url convinient
2. keep the "save" button on the next row, fixed to the right 

![b39](https://user-images.githubusercontent.com/51397558/71238974-6eefda00-232b-11ea-96ea-9848b241db9c.png)

@jeromie kindly review the suggestion

**Comment by jeromie** [comment]
yes, a good suggestion.
